## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df.drop(["EIN", "NAME"], axis=1, inplace=True)

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 500
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
CLASSIFICATION_value_counts=application_df["CLASSIFICATION"].value_counts()
CLASSIFICATION_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_value_counts_greater_than_1 = CLASSIFICATION_value_counts[CLASSIFICATION_value_counts > 1]
classification_value_counts_greater_than_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1000

classification_value_counts = application_df["CLASSIFICATION"].value_counts()
classifications_to_replace = classification_value_counts[classification_value_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
from sklearn.model_selection import train_test_split
X = application_df.drop(columns=['IS_SUCCESSFUL'])  # Features (remove target column)
y = application_df['IS_SUCCESSFUL']  # Target

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=69)
X.shape

(34299, 43)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation="tanh",input_dim=43))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=40, activation="tanh"))
nn.add(tf.keras.layers.Dense(units=20, activation="tanh"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 40)                3240

 dense_2 (Dense)             (None, 20)                820

 dense_3 (Dense)             (None, 1)                 21

=================================================================
Total params: 7,601
Trainable params: 7,601
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam",metrics=["accuracy"])

In [14]:
# Train the model
#  YOUR CODE GOES HERE
fit_model=nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 7s 6ms/step - loss: 0.5691 - accuracy: 0.7224
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5579 - accuracy: 0.7275
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5546 - accuracy: 0.7287
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5521 - accuracy: 0.7301
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5516 - accuracy: 0.7298
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7305
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7325
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7312
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7334
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7329
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7343
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7350
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7332
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7347
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7352
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7352
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7361
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7361
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7372
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7365
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7374
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7361
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7375
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7374
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7371
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7382
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7381
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7389
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7375
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7382
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7385
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7381
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7379
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7383
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7388
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7393
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7381
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7379
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7385
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7393
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7385
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7386
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7388
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7396
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7391
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7391
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7395
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7400
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7383
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7402
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7390
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7400
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7398
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7390
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7393
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7392
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7401
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7399
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7399
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7395
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7405
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7390
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7397
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7396
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7400
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7399
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7389
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.7398
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7395
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7386
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7399
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7391
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7403
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7404
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7403
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7398
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7399
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7398
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7399
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7395
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7406

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5548 - accuracy: 0.7333 - 493ms/epoch - 2ms/step
Loss: 0.5548480153083801, Accuracy: 0.7332944869995117

In [16]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('AlphabetSoupCharity.h5')